// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lesson1.Data;

#nullable disable

namespace lesson1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lesson1.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "Nike",
                            Color = "Red",
                            Gender = "Men",
                            Size = 42,
                            price = 3.0
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "Nike",
                            Color = "Blue",
                            Gender = "Men",
                            Size = 42,
                            price = 33.0
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "Nike",
                            Color = "Pink",
                            Gender = "Men",
                            Size = 42,
                            price = 23.0
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "Nike",
                            Color = "Yello",
                            Gender = "Men",
                            Size = 42,
                            price = 63.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
